export interface Material {
    uid                 : string,
    supplierSKU?        : string,
    manufacterSKU?      : string,
    serialNumber?       : string,
    description         : string,
    brand               : string,
    division            : string,
    subDivision?        : string,
    measurementUnit     : string,
    quantityInDeposit   : number,
    quantityOnTransit?  : number,
    quantityOrdered?    : number,
    quantityOwed?       : number,
    quantityDelivered?  : number,
    inboundDate?        : string,
    outboundDate?       : string,
    etaDate?            : string,
    minStock?           : number,
    requestPoint?       : number,
    eDeliveryTime?      : number,          
}